/*
* File name: GaborNameDialogImp.h
*/

#ifndef __GABOR_NAME_DIALOG_H__
#define __GABOR_NAME_DIALOG_H__

// Temporary file generated by Qt from UI file
#include "ui_GaborNameDialog.h"

/**
* Dialog to display / edit name information for gabor configurations.
*/
class GaborNameDialogImp : public QDialog, public Ui::GaborNameDialog
{
	Q_OBJECT
public:
	/**
	* Default constructor.
	*/
	GaborNameDialogImp( QWidget *parent = 0);

	/**
	* Default destructor.
	*/
	~GaborNameDialogImp();
private:
};

#endif
